### GET blogs
GET {{backend_api}}/blog

### GET blog
GET {{backend_api}}/blog/1

### POST blog
POST {{backend_api}}/blog
Content-Type: application/json

{
  "title": "Blog title",
  "content": "Blog content",
  "thumbnailUrl": "https://cdn.hannah-log.site/cdn/python.jpg",
  "tagIds": [1, 2, 3]
}

### PATCH blog
PATCH {{backend_api}}/blog/1
Content-Type: application/json

{
  "title": "Blog title update",
  "content": "Blog content update",
  "thumbnailUrl": "https://cdn.hannah-log.site/cdn/python.jpg",
  "tagIds": [1, 2, 3]
}

### DELETE blog
DELETE {{backend_api}}/blog/1
